# Generated by Django 5.2.16 on 2026-09-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('photo', models.CharField(max_length=50)),
            ],
        ),
    ]
