# Generated by Django 5.2.16 on 2026-09-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_contactbook_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactbook',
            name='course',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
