# Generated by Django 5.2.16 on 2026-09-14 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contactbook_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactbook',
            name='course',
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('CONTACTBOOK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contactbook')),
            ],
        ),
    ]
