# Generated by Django 5.2.16 on 2026-09-14 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_contactbook_course_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='CONTACTBOOK',
        ),
        migrations.AddField(
            model_name='contactbook',
            name='COURSES',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.courses'),
            preserve_default=False,
        ),
    ]
