# Generated by Django 5.2.16 on 2026-09-15 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactbook',
            name='COURSES',
        ),
        migrations.AddField(
            model_name='contactbook',
            name='SUBJECTS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.subjects'),
            preserve_default=False,
        ),
    ]
